**工程完整信息与更多演示：**
- 博主个人主页：[三余知行官方网站](https://threefish.site/trend)
- GitHub Repo：[ThreeFish-AI/deep-learning](https://github.com/ThreeFish-AI/deep-learning)

# 逻辑运算

In [2]:
import numpy as np

In [3]:
def AND(x1, x2):
    """
    感知机 AND Gate 计算逻辑
    """
    x = np.array([x1, x2]).T
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.dot(x, w) + b  # 等效于 x1 * w1 + x2 * w2 + b
    return np.where(tmp <= 0, 0, 1)

print('测试单组 (x1, x2) 的与运算：')
print(AND(0, 0))  # 0
print(AND(1, 0))  # 0
print(AND(0, 1))  # 0
print(AND(1, 1))  # 1

print('测试多组 (x1, x2) 的与运算：')
x1 = np.array([0, 1, 0, 1])
x2 = np.array([0, 0, 1, 1])
print(AND(x1, x2))  # 0,0,0,1

测试单组 (x1, x2) 的与运算：
0
0
0
1
测试多组 (x1, x2) 的与运算：
[0 0 0 1]


In [4]:
def NAND(x1, x2):
    """
    使用 numpy 实现（可批量计算的）感知机 NAND Gate 计算逻辑
    """
    x = np.array([x1, x2]).T
    w = np.array([-0.5, -0.5])
    b = 0.7
    tmp = np.dot(x, w) + b  # 等效于 x1 * w1 + x2 * w2 + b
    return np.where(tmp <= 0, 0, 1)

print('测试单组 (x1, x2) 的与非运算：')
print(NAND(0, 0))  # 1
print(NAND(1, 0))  # 1
print(NAND(0, 1))  # 1
print(NAND(1, 1))  # 0

print('测试多组 (x1, x2) 的与非运算：')
x1 = np.array([0, 1, 0, 1])
x2 = np.array([0, 0, 1, 1])
print(NAND(x1, x2))  # 1,1,1,0

测试单组 (x1, x2) 的与非运算：
1
1
1
0
测试多组 (x1, x2) 的与非运算：
[1 1 1 0]


In [5]:
def OR(x1, x2):
    """
    使用 numpy 实现（可批量计算的）感知机 OR Gate 计算逻辑
    """
    x = np.array([x1, x2]).T
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.dot(x, w) + b  # 等效于 x1 * w1 + x2 * w2 + b
    return np.where(tmp <= 0, 0, 1)

print('测试单组 (x1, x2) 的或运算：')
print(OR(0, 0))  # 0
print(OR(1, 0))  # 1
print(OR(0, 1))  # 1
print(OR(1, 1))  # 1

print('测试多组 (x1, x2) 的或运算：')
x1 = np.array([0, 1, 0, 1])
x2 = np.array([0, 0, 1, 1])
print(OR(x1, x2))  # 0,1,1,1

测试单组 (x1, x2) 的或运算：
0
1
1
1
测试多组 (x1, x2) 的或运算：
[0 1 1 1]


In [6]:
def XOR(x1, x2):
    """
    使用 与、或、非 逻辑运算组合实现感知机 XOR gate 计算逻辑
    """
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    return AND(s1, s2)

print('测试单组 (x1, x2) 的异或运算：')
print(XOR(0, 0))  # 0
print(XOR(1, 0))  # 1
print(XOR(0, 1))  # 1
print(XOR(1, 1))  # 0

print('测试多组 (x1, x2) 的异或运算：')
x1 = np.array([0, 1, 0, 1])
x2 = np.array([0, 0, 1, 1])
print(XOR(x1, x2))  # 0,1,1,0

测试单组 (x1, x2) 的异或运算：
0
1
1
0
测试多组 (x1, x2) 的异或运算：
[0 1 1 0]


# 感知机训练

In [8]:
import numpy as np

class Perceptron:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        """
        初始化学习率、迭代次数、权重和偏置。
        """

        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        """
        训练模型。对每个训练样本，计算预测值并更新权重和偏置。
        """

        # 初始化权重和偏置
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        # 训练过程
        for _ in range(self.n_iterations):
            for idx, x_i in enumerate(X):
                # 计算加权和并应用阶跃函数
                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.activation_function(linear_output)

                # 更新规则
                update = self.learning_rate * (y[idx] - y_predicted)
                self.weights += update * x_i
                self.bias += update

    def activation_function(self, x):
        """
        使用阶跃函数作为激活函数。
        """
        return 1 if x >= 0 else 0

    def predict(self, X):
        """
        根据训练好的权重和偏置，返回预测结果。
        """
        linear_output = np.dot(X, self.weights) + self.bias
        return [self.activation_function(i) for i in linear_output]

# 示例数据：逻辑与操作的训练数据
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])  # 逻辑与的标签

# 创建感知机实例并训练
perceptron = Perceptron(learning_rate=0.1, n_iterations=10)
perceptron.fit(X, y)

# 进行预测
predictions = perceptron.predict(X)
print("预测结果：", predictions)
# 预测结果： [0, 0, 0, 1]

预测结果： [0, 0, 0, 1]


**工程完整信息与更多演示：**
- 博主个人主页：[三余知行官方网站](https://threefish.site/trend)
- GitHub Repo：[ThreeFish-AI/deep-learning](https://github.com/ThreeFish-AI/deep-learning)